apiVersion: apps/v1
kind: Deployment
metadata:
  name: n646887-notes-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: n646887-notes-api
  template:
    metadata:
      labels:
        app: n646887-notes-api
    spec:
      containers:
        - name: notes-api
          image: ingvildforseth/n646887-notes-api:v0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: n646887-notes-api
spec:
  type: LoadBalancer
  selector:
    app: n646887-notes-api
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n646887-notes-api
  namespace: n646887-kurs
  annotations:
    nginx.ingress.kubernetes.io/enable-global-auth: "false"
spec:
  rules:
    - host: notes-api.plattform-int.eno.k8s-kurs.az.nrk.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n646887-notes-api
                port:
                  number: 80
